version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sustainability_db
    restart: always
    environment:
      POSTGRES_DB: city_data
      POSTGRES_USER: datpham
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9
    container_name: flyway_migration
    depends_on:
      - postgres
    command: ["migrate"]
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/sustainability
      FLYWAY_USER: datpham
      FLYWAY_PASSWORD: 123456
      FLYWAY_LOCATIONS: filesystem:/flyway/sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sustainability_backend
    depends_on:
      - postgres
      - flyway
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sustainability
      SPRING_DATASOURCE_USERNAME: datpham
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"

volumes:
  postgres_data:
