spring:
  application:
    name: Sustainability

  main:
    allow-bean-definition-overriding: true

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

  datasource:
    url: jdbc:postgresql://postgres:5432/sustainability
    username: datpham
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 10
      minimumIdle: 3

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
